### ISSUE TITLE
report an error in "Introduction to gghighlight" (unhighlighted_params)

### ISSUE THREAD

**Issue by sunxm19** [yutannihilation/gghighlight#107]
I am following your example in [introduction](https://yutannihilation.github.io/gghighlight/articles/gghighlight.html) page, and the sample code for  `unhighlighted_params ` seems not working.
I am wondering something missed in your example code.
```
Error: Column `p2` must be length 20 (the number of rows) or one, not 2
In addition: Warning message:
You set use_group_by = TRUE, but grouped calculation failed.
Falling back to ungrouped filter operation...
```

**Comment by yutannihilation** [comment]
Do you use the dev version? CRAN version doesn't have that option.

**Comment by sunxm19** [comment]
Thanks for the reply. I use the dev version of Rstudio, and I exactly followed your instruction, installed the CRAN version. I will try on another computer and will let you know the results soon.

**Comment by yutannihilation** [comment]
I mean the dev version of gghighlight, which you can install by `devtools::install_github()`.

**Comment by sunxm19** [comment]
No, I didn't use the `devtools::install_github()` to install the `dev` edition of `gghighlight`. The reason for this error is related to this line: `colour = alpha("pink", 0.4))`. If I delete this line, a slightly different graph can be made on my computer: 
```
ggplot(d) +
  geom_line(aes(idx, value, colour = type), size = 5) +
  gghighlight(max(value) > 19,
              unhighlighted_params = list(size = 1))
```

Additionally, my last graph produced using the following code is slightly different from yours: 
```
p +
  gghighlight(max(value) > 10, use_facet_vars = TRUE) +
  ggtitle("use_facet_vars = TRUE")
```
I will update my results soon on another computer. Thanks for your reply. It is really a great and powerful package. I like it a LOT!

**Comment by yutannihilation** [comment]
Again, the CRAN version of gghighlight doesn't have these options. https://yutannihilation.github.io/gghighlight/articles/gghighlight.html is the documentation for the dev version, so you need the dev version to reproduce the result. If you stick with the CRAN version, please read the CRAN version of vignette here: https://cran.r-project.org/web/packages/gghighlight/vignettes/gghighlight.html. Sorry for your confusion!
