### ISSUE TITLE
Two pridicates result in labels but no highlights

### ISSUE THREAD

**Issue by chalg** [yutannihilation/gghighlight#111]
The below code creates labels correctly, but does not highlight associated lines. Should I install the dev version, rather than CRAN?
gghighlight(Date >= as_date("2019-06-01"), Value < 100)
If I only have one predicate it works as expected.

**Comment by yutannihilation** [comment]
Could you provide a reprex?

**Comment by chalg** [comment]
OK, operator error - worked it out.
