### ISSUE TITLE
Replace dplyr's scoped variants to across()

### ISSUE THREAD

**Issue by yutannihilation** [yutannihilation/gghighlight#122]

**Comment by bersbersbers** [comment]
Will that resolve the
> Using `across()` in `filter()` is deprecated, use `if_any()` or `if_all()`. 

warnings? That would be great.

**Comment by yutannihilation** [comment]
Oh, no. This issue is already addressed by https://github.com/yutannihilation/gghighlight/commit/b586c18d14b4dbd3a907f1e18c04c140ffca2b56, but I didn't notice the warning. Thanks for the comment!

Let me close this issue and file a new one.
