### ISSUE TITLE
retain color of unhighlighted data

### ISSUE THREAD

**Issue by whtns** [yutannihilation/gghighlight#134]
I was formerly able to use `unhighlighted_colour = NULL` to retain the color of unhighlighted data. I am now not able to do so using either `unhighlighted_params = list(color = NULL)` or `unhighlighted_params = list(color = {var})`

Is this still possible? Could you include an example demonstrating this option?

# reprex
```
mtcars2 <- mtcars %>% 
  dplyr::mutate(circled = qsec > 18)

ggplot(mtcars2, aes(x = cyl, y = mpg)) +
  geom_point(aes(color = gear)) +
  gghighlight(circled == TRUE, use_direct_label = FALSE, unhighlighted_params = list(color = NULL)) +
  geom_point(pch=21, fill=NA, size=3, colour="black", stroke=0.5) +
# scale_x_discrete(labels = paste0(seq(length(snp_id), snp_id))) +
NULL  
```

**Comment by yutannihilation** [comment]
Thanks for reporting! In this case, you want to highlight just some of the layers and leave others as is, right? If so, you can specify `n` to limit the number of layers above to modify.

``` r
library(gghighlight)
#> Loading required package: ggplot2
library(dplyr, warn.conflicts = FALSE)

mtcars2 <- mtcars %>% 
  dplyr::mutate(circled = qsec > 18)

ggplot(mtcars2, aes(x = cyl, y = mpg)) +
  geom_point(aes(color = gear)) +
  geom_point(pch=21, fill=NA, size=3, colour="black", stroke=0.5) +
  gghighlight(circled == TRUE, use_direct_label = FALSE, n = 1)
```

![](https://i.imgur.com/EJEBA6D.png)

<sup>Created on 2020-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by whtns** [comment]
Thanks for this quick response. That's exactly what I'm looking for!
