### ISSUE TITLE
Cannot sort by min

### ISSUE THREAD

**Issue by antonwnk** [yutannihilation/gghighlight#148]
My use-case involves using a non-logical predicate with `max_highlight` to highlight the lowest values in my set of lines, however, I find that replacing the max function in the vignette example with min does not work and still outputs the max:
```
set.seed(2)
d <- purrr::map_dfr(
  letters,
  ~ data.frame(
      idx = 1:400,
      value = cumsum(runif(400, -1, 1)),
      type = .,
      flag = sample(c(TRUE, FALSE), size = 400, replace = TRUE),
      stringsAsFactors = FALSE
    )
)

ggplot(d, aes(idx, value, colour = type)) +
  geom_line() +
  gghighlight(min(value), max_highlight = 5L)
```
![000011](https://user-images.githubusercontent.com/23464453/80282840-f1423d80-8713-11ea-903c-053c38a25033.png)

It does work to use `-max(.)` instead of `min(.)` (i.e. something else gets plotted) but that's not equivalent, unfortunately, as it only reverses the order of the _maximum_ values in each line.

**Comment by yutannihilation** [comment]
Ah, it might be a bit tricky. By using `min()`, you are highlighting the lines whose minimum values are the highest. I guess what you want is `-min()`, right?

**Comment by antonwnk** [comment]
Ahh! That's right, my mistake.
Thanks for clearing it up. 😀
