### ISSUE TITLE
ggplotly tooltip issue

### ISSUE THREAD

**Issue by rbratslaver** [yutannihilation/gghighlight#150]
Hi - it looks like gghighlight is duplicating values in the plotly tooltip; do you have a suggested workaround?

```
gapminder::gapminder %>% 
  group_by(continent,year) %>% 
  summarise(life=mean(lifeExp)) %>% 
  ungroup() %>% 
ggplot(aes(year,life,color=continent))+
geom_line(size=1.5)+
gghighlight(continent%in%c('Africa','Europe'),use_direct_label = F,
            use_group_by = F)->p

ggplotly(p)
```

![image](https://user-images.githubusercontent.com/32785182/82395139-db751f00-9a18-11ea-9f35-683595f608d9.png)

**Comment by yutannihilation** [comment]
Hmm, unfortunately, it is what it is. There's no workaround, but you can live without gghighlight:

``` r
gapminder::gapminder %>% 
  group_by(continent,year) %>% 
  summarise(life=mean(lifeExp)) %>% 
  ungroup() %>% 
  ggplot(
    aes(year, life,
      group = continent,
      color = if_else(continent %in% c('Africa','Europe'), as.character(continent), NA_character_)
    )
  ) +
  geom_line(size=1.5)
```

If you are interested in the internals, please read:

https://yutani.rbind.io/post/2018-06-03-anatomy-of-gghighlight/
