### ISSUE TITLE
Issues with next ggplot2 release

### ISSUE THREAD

**Issue by thomasp85** [yutannihilation/gghighlight#165]
Hi Hiroaki

There are some issues in the tests of gghighlight with the next ggplot2 version, related to the changes in PositionJitter

Can I get you to look into whether it is an issue in gghighlight or ggplot2

best
Thomas

**Comment by yutannihilation** [comment]
Thanks. I noticed this some days ago, but haven't had time to look into it so far, sorry. I expect this is just the tests aren't quite right and this isn't the issue on ggplot2's side. I'll investigate later.

**Comment by yutannihilation** [comment]
Fixed the test on master, and I'll release soon. It turned out this was because of a workaround for tidyverse/ggplot2#2507, which is now fixed on ggplot2's side.
