### ISSUE TITLE
Documentation Example uses undefined data variable

### ISSUE THREAD

**Issue by evensolberg** [yutannihilation/gghighlight#173]
The examples in the README.md use the variable `d` for data, but nowhere is `d` actually defined.

If this is just a "random" data set, perhaps the example could be reworked with actual data, such as mtcars?

**Comment by yutannihilation** [comment]
Oh, good point, thanks. Currently the data is generated by this code, which I felt a bit too long to show:

https://github.com/yutannihilation/gghighlight/blob/3808493e9de3fb10a73b442e473cb4a8523c1bf2/README.Rmd#L39-L49

I don't think `mtcars` is a good example data for gghighlight. We need some more messy data like the current one. Feel free to suggest a nice one!

**Comment by evensolberg** [comment]
That chunk isn't that long IMHO. Especially if you just put it in a separate paragraph initially.

**Comment by yutannihilation** [comment]
Imho, this is too long.

**Comment by yutannihilation** [comment]
Just in case you don't notice, I included it in the getting started vignette.

https://yutannihilation.github.io/gghighlight/articles/gghighlight.html

**Comment by evensolberg** [comment]
I did not. Thanks. Perhaps a quick note about that could be placed near the top of the README? That would take care of it nicely. :-)
