### ISSUE TITLE
multiple predicates don't work

### ISSUE THREAD

**Issue by daranzolin** [yutannihilation/gghighlight#174]
Reprex::

``` r
library(gghighlight)
#> Warning: package 'gghighlight' was built under R version 4.0.5
#> Loading required package: ggplot2

set.seed(2)
d <- purrr::map_dfr(
  letters,
  ~ data.frame(
    idx = 1:400,
    value = cumsum(runif(400, -1, 1)),
    type = .,
    flag = sample(c(TRUE, FALSE), size = 400, replace = TRUE),
    stringsAsFactors = FALSE
  )
)

ggplot(d) +
  geom_line(aes(idx, value, colour = type)) +
  gghighlight(max(value) > 15, mean(flag) > 0.55)
#> label_key: type
```

![](https://i.imgur.com/iOe8nom.png)

<sup>Created on 2021-07-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by yutannihilation** [comment]
Hi, I guess you are suggesting to fix the code on the vignette, but it's already fixed by this commit: https://github.com/yutannihilation/gghighlight/commit/08992037c44423adec49bb2caa215c6dd4dff7d5

Thanks for your report anyway!
