### ISSUE TITLE
Allow highlighting of entry in legend

### ISSUE THREAD

**Issue by gdevenyi** [yutannihilation/gghighlight#182]
I'd like to be able to retain the legend, while applying something like unhighlighted_params to non-highlighted entries.

**Comment by yutannihilation** [comment]
Thanks for the suggestion, but, due to a design decision to support facetting, this is not possible, unfortunately. I expect you can achieve this with a plain ggplot2, though!

**Comment by gdevenyi** [comment]
>  I expect you can achieve this with a plain ggplot2, though!

Would love a pointer at where to find this kind of thing in the docs!

**Comment by yutannihilation** [comment]
https://ggplot2.tidyverse.org/reference/scale_manual.html

or

https://ggplot2.tidyverse.org/reference/aes_eval.html

**Comment by gdevenyi** [comment]
if anyone ever comes looking, this is the place to do it
https://aosmith.rbind.io/2020/07/09/ggplot2-override-aes/
