### ISSUE TITLE
Weird failure with dev purrr

### ISSUE THREAD

**Issue by hadley** [yutannihilation/gghighlight#186]
``` r
library(ggplot2)
library(gghighlight)

ggplot(mtcars, aes(wt, mpg, colour = factor(cyl))) +
  geom_point() +
  gghighlight(100 < disp, disp <= 300, use_group_by = FALSE)
#> label_key: NULL
#> Error in `ggrepel::geom_label_repel()`:
#> ! Problem while setting up geom.
#> ℹ Error occurred in the 3rd layer.
#> Caused by error in `compute_geom_1()`:
#> ! `geom_label_repel()` requires the following missing aesthetics: label
```

<sup>Created on 2022-09-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Any ideas what might going wrong here? I'm happy to help if you can point me to where the problem might be coming from

**Comment by yutannihilation** [comment]
Thanks for the report, I'll investigate.

**Comment by yutannihilation** [comment]
Here's the subtle difference that matters. My code assumed it's `NULL` when the subsetted `uneval` object is empty. Using `is_empty()` should fix the issue (https://github.com/yutannihilation/gghighlight/pull/190/commits/59c77dce1dd8e42c339c5fd7b600737d6a3a9581).

### w/ the CRAN version of purrr

``` r
x <- list(
  list(key = ggplot2::aes()),       # different result
  list(key = ggplot2::aes(x = foo)) # same result
)

purrr::map(x, "key")
#> [[1]]
#> NULL
#> 
#> [[2]]
#> Aesthetic mapping: 
#> * `x` -> `foo`

packageVersion("purrr")
#> [1] '0.3.4'
```

<sup>Created on 2022-10-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### w/ the dev version of purrr

``` r
x <- list(
  list(key = ggplot2::aes()),       # different result
  list(key = ggplot2::aes(x = foo)) # same result
)

purrr::map(x, "key")
#> [[1]]
#> Aesthetic mapping: 
#> <empty>
#> 
#> [[2]]
#> Aesthetic mapping: 
#> * `x` -> `foo`

packageVersion("purrr")
#> [1] '0.9000.0.9000'
```

<sup>Created on 2022-10-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Thanks for looking into this! This was a deliberate change to `pluck()`: https://github.com/tidyverse/purrr/pull/893
