### ISSUE TITLE
The example is faulty

### ISSUE THREAD

**Issue by alireza5969** [yutannihilation/gghighlight#202]
The following example which is provided on the `Introduction to gghighlight` [page](https://yutannihilation.github.io/gghighlight/articles/gghighlight.html#labels:~:text=%3D%20list(-,linewidth,-%3D%2010)) is not correct:

```r
ggplot(d) +
    geom_line(aes(idx, value, colour = type)) +
    gghighlight(max(value) > 20, label_params = list(linewidth = 10))
```
The `linewidth` parameter is for lines not for labels. Therefore, when you run the code, the following warning will be shown by `R`:
``
Warning message:
In geom(mapping, rightmost_points, linewidth = 10) :
  Ignoring unknown parameters: `linewidth`
``

**Comment by yutannihilation** [comment]
Thanks for letting me know! It was my mistake when I replaced some `size` to `linewidth` in the doc.
