### ISSUE TITLE
highlighting by group in a `geom_boxplot` adds highlighted points as duplicates over the old ones, instead of highlighting them

### ISSUE THREAD

**Issue by Gewerd-Strauss** [yutannihilation/gghighlight#212]
Hello,

I am not sure if I am just really not understanding the `gghighlight()`-function, but this behaviour seems very wrong.

Assume you create a boxplot as below:

```R
# Load required libraries
library(ggplot2)
library(gghighlight)

# Create a simple dataset with 10 data points per group
set.seed(123)
Data_test <- data.frame(
    Group = rep(c("A", "B", "C", "D"), each = 5),
    Group2 = rep(c("A", "B", "C", "D"), each = 5),
    Value = c(seq(1,5), 
              seq(1,5), 
              seq(1,5), 
              seq(1,5))
)

# Create the original boxplot
test_plot <- ggplot(data = Data_test, aes(x = Group, y = Value, fill = Group2)) +
    geom_boxplot() +
    geom_jitter(height = 0) +
    theme_minimal() +
    labs(title = "Test Boxplot Grouped by Group Variable",
         x = "Group",
         y = "Value")


```

This renders to a wonderfully simple plot:

![grafik](https://github.com/user-attachments/assets/68e0c258-deff-4a8e-98e1-70026ed0af84)

```R
# Apply gghighlight to highlight Group C
highlight_plot <- test_plot + gghighlight(
    Group == "B",
    use_direct_label = F,
    calculate_per_facet = F,
    # unhighlighted_params = aes(fill = NULL)
)

# compare
#print(test_plot)
#print(highlight_plot)

# Why does Group 'B' suddenly have 10 datapoints? 
# Why are the added datappoints at different 

```

But when I try and highlight by group, this happens:

![grafik](https://github.com/user-attachments/assets/d725e25c-c154-4bf7-8bb0-95a9888401c2)

I have two issues currently:

1. The legend lost the entries for the other groups - I suppose this makes sense, I'd just like to overwrite that behaviour.
2. More important though, group `B` now has twice as many points - the highlighted ones, and the muted gray ones. 

I don't understand why issue 2 occurs, because conceptually to me just makes no sense. If I wanted to highlight a group, I can't have them be rendered in duplicates and materialise observations out of nothing.

How can I resolve this? 

Thank you.
Sincerely,
~Gw

**Comment by Gewerd-Strauss** [comment]
I have found out that I can also perform the following to keep the other groups coloured. Additionally, in the highlighted group there are now no duplicates (that is, only the highlighted points are shown).

Unfortunately, this will also strip the points for all other groups, leaving only the raw boxes of the geom_boxplot behind - and even that is not completely shown:


```R
# Apply gghighlight to highlight Group B
highlight_plot2 <- test_plot +  gghighlight::gghighlight(Group == "B",use_group_by = F,calculate_per_facet = T,keep_scales = T,unhighlighted_params = aes(colour = NA,fill=NULL),use_direct_label = F,)

# compare
#print(test_plot)
#print(highlight_plot)
#print(highlight_plot2)

# Why does Group 'B' suddenly have 10 datapoints? 
# Why are the added datappoints at different 

```

![grafik](https://github.com/user-attachments/assets/182f9f47-22d7-469b-b530-d0c856b32208)

**Comment by yutannihilation** [comment]
One thing you need to do is to fix the seed of jitter via `position_jitter()`, but it seems it doesn't save you. Probably, the width of the jitter depends on the whole data in the case of a discrete scale.

Probably, this is a won't fix at least on gghighlight's side.

``` r
library(ggplot2)
library(gghighlight)

Data_test <- data.frame(
    Group = rep(c("A", "B", "C", "D"), each = 5),
    Group2 = rep(c("A", "B", "C", "D"), each = 5),
    Value = c(seq(1,5), 
              seq(1,5), 
              seq(1,5), 
              seq(1,5))
)

do_plot <- function(filter_func) {
  ggplot(data = Data_test, aes(x = Group, y = Value, fill = Group2)) +
    geom_point(position = position_jitter(height = 0, seed = 123), color = alpha("red", 0.6), size = 10) +
    geom_point(data = filter_func,
      position = position_jitter(height = 0, seed = 123), colour = alpha("blue", 0.6), size = 10) +
    theme_minimal() +
    guides(fill = "none")
}

do_plot(identity)
```

![](https://i.imgur.com/0LrzPE1.png)

``` r
do_plot(\(d) dplyr::filter(d, Group == "B"))
```

![](https://i.imgur.com/rFnqfK3.png)

<sup>Created on 2024-10-01 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by yutannihilation** [comment]
>  in the case of a discrete scale.

Sorry, I was wrong. It seems jitter simply doesn't match when the whole data that the points belong to are different.

``` r
library(ggplot2)

jitter <- position_jitter(width = 0.3, height = 0.3, seed = 0)
ggplot(mtcars, aes(am, vs)) +
  geom_point(position = jitter, size = 4, colour = alpha("red", 0.6)) +
  geom_point(data = \(d) dplyr::filter(d, am < 0.5 & vs < 0.4),
             position = jitter, size = 4, colour = alpha("blue", 0.6))
```

![](https://i.imgur.com/AkC3eFA.png)

<sup>Created on 2024-10-01 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by yutannihilation** [comment]
Hmm, I thought jitter works with gghighlight to some extent, but it seems I found no hope in the past... 

https://github.com/yutannihilation/gghighlight/issues/38

So, let me close this issue as this is a won't fix. Sorry for your confusion!

**Comment by Gewerd-Strauss** [comment]
I am not sure I completely follow along; but do I undestand correctly that this is simply just not possible then?

**Comment by yutannihilation** [comment]
Yes, that's what I meant. You can manually add jitter (also change X axis as continuous).

**Comment by Gewerd-Strauss** [comment]
Alright, thank you for the clarification.
