### ISSUE TITLE
Incompatibility with geom_errorbar?

### ISSUE THREAD

**Issue by nathant181** [yutannihilation/gghighlight#213]
Hi, thanks for your great package! The following code works as expected:

`test = data.frame(cat = c("a", "b", "c", "d", "e"), point = c(1, 3, 2, 6, 1), lcl = c(0.8, 2.5, 1.9, 5.6, 0.9), ucl = c(1.2, 3.3, 2.1, 6.4, 1.1))`

`ggplot(test, aes(x = cat, y = point)) +
  geom_col() +
  geom_errorbar(ymax = test$ucl, ymin = test$lcl, width = 0.2) +
  coord_cartesian(ylim = c(0, max(test$ucl)))`

The following also works, with a nice highlight on the required bar:

`ggplot(test, aes(x = cat, y = point)) +
  geom_col() +
  coord_cartesian(ylim = c(0, max(test$ucl))) +
  gghighlight(cat == "a")`

The following does not work:

`ggplot(test, aes(x = cat, y = point)) +
  geom_col() +
  geom_errorbar(ymax = test$ucl, ymin = test$lcl, width = 0.2) +
  coord_cartesian(ylim = c(0, max(test$ucl))) +
  gghighlight(cat == "a")`

Error message:

`Error in `geom_errorbar()`:`
`! Problem while setting up geom aesthetics.`
`i Error occurred in the 4th layer.`
`Caused by error in `check_aesthetics()`:`
`! Aesthetics must be either length 1 or the same as the data (1).`
`x Fix the following mappings: `ymin` and `ymax`.`
`Run `rlang::last_trace()` to see where the error occurred.`

Am I doing something wrong?

**Comment by trekonom** [comment]
You can fix your issue by mapping on aesthetics instead of passing the dataset columns to parameters (which I would recommend to avoid in general):

``` r
test <- data.frame(cat = c("a", "b", "c", "d", "e"), point = c(1, 3, 2, 6, 1), lcl = c(0.8, 2.5, 1.9, 5.6, 0.9), ucl = c(1.2, 3.3, 2.1, 6.4, 1.1))

library(gghighlight)
#> Loading required package: ggplot2
library(ggplot2)

ggplot(test, aes(x = cat, y = point)) +
  geom_col() +
  geom_errorbar(aes(ymax = ucl, ymin = lcl), width = 0.2) +
  coord_cartesian(ylim = c(0, max(test$ucl))) +
  gghighlight(cat == "a")
```

![](https://i.imgur.com/EVjCLvw.png)

<sup>Created on 2024-12-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by yutannihilation** [comment]
Thanks @trekonom!

Yes, gghighlight can only handle columns specified via `aes()`. Technically, it might be possible to support such a vector input, but I don't think it's worth as it's not the recommended usage of ggplot2. If you are looking for a good resource to learn ggplot2, the ggplot2 book might be the one. Hope this helps!

https://ggplot2-book.org/
