### ISSUE TITLE
Advice to use `seed` for position_jitter()

### ISSUE THREAD

**Issue by yutannihilation** [yutannihilation/gghighlight#38]
### Bad

``` r
library(ggplot2)
library(gghighlight)

ggplot(mpg, aes(cyl, hwy, colour = year)) +
  geom_jitter() + 
  geom_highlight(max(cyl) > 4, use_direct_label = FALSE)
```

![](https://i.imgur.com/fE53Crj.png)

### Good

``` r
ggplot(mpg, aes(cyl, hwy, colour = year)) +
  geom_jitter(position = position_jitter(seed = 1)) + 
  geom_highlight(max(cyl) > 4, use_direct_label = FALSE)
```

![](https://i.imgur.com/uv6OL8h.png)

**Comment by yutannihilation** [comment]
Hmm...?

``` r
library(ggplot2)
library(gghighlight)

ggplot(mpg, aes(cyl, hwy, colour = year)) +
  geom_jitter(position = position_jitter(seed = 1)) + 
  geom_highlight(hwy > 30, use_direct_label = FALSE)
```

![](https://i.imgur.com/IzPml19.png)

``` r

ggplot(mpg, aes(cyl, hwy, colour = year)) +
  geom_jitter(position = position_jitter(seed = 1)) + 
  geom_highlight(hwy > 30, use_direct_label = FALSE)
```

![](https://i.imgur.com/66Hka0V.png)

Created on 2018-06-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
Something is very strange.

``` r
library(ggplot2)
library(gghighlight)
library(patchwork)

p <- ggplot(mpg, aes(cyl, hwy, colour = year)) +
  geom_jitter(position = position_jitter(seed = 1)) 

p / p + geom_highlight(hwy > 30, use_direct_label = FALSE)
```

![](https://i.imgur.com/iQYbr3P.png)

Created on 2018-06-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
This gonna be a bit tough job. Close this for now.

**Comment by bart1** [comment]
Just a quick note on this, I just encountered the issue in my own code. @yutannihilation : From the fact that this issue was closed without resolution I assume this is still unsolved?

**Comment by yutannihilation** [comment]
Yes, I concluded this cannot be fixed.

**Comment by yutannihilation** [comment]
If you really want to do this, you can manually add jittering to the original data instead of position_jitter().

**Comment by bart1** [comment]
That is a good idea! I however I use it for a discrete scale on the x axis so that might be slightly more tricky.

**Comment by yutannihilation** [comment]
Ah, I see....
