### ISSUE TITLE
Please make gghighilght work with ggrepel

### ISSUE THREAD

**Issue by sjcowtan** [yutannihilation/gghighlight#89]
Hi,
I love gghighlight but when I am working with scatterplots I end up not using it because the labels end up all over the points. I use ggrepel to keep them separate and readable.  Is there any chance you could make gghighlight work with ggrepel? 
S

**Comment by yutannihilation** [comment]
Maybe you are unaware of `use_direct_labels`?

https://yutannihilation.github.io/gghighlight/articles/gghighlight.html#labels

**Comment by yutannihilation** [comment]
@sjcowtan I'm closing this. If you feel `use_direct_labels` is not enough, please feel free to reopen with a [reprex](https://www.tidyverse.org/help/). Thanks!
